config/routes.rb
ScrawlSite3::Application.routes.draw do
  
  get "apps/new"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :scrawls,       only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :apps 
  
  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/terms',   to: 'static_pages#terms'

end

app/views/shared/_background_user_info.html.erb
<span>
  <%= current_user.handle %>
</span>
<span>
  <%= current_user.tagline %>
</span>
<span>
  <%= current_user.location %>
</span>
<span>
  <a href="http:www.facebook.com/petegrif">My Facebook Page</a>
</span>
<span>
  <%= current_user.likes %>
</span>
<span>
  <%= current_user.dislikes %>
</span>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="scrawls">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= wrap(feed_item.content) %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method:  :delete,
                                     confirm: "You sure?",
                                     title:   feed_item.content %>
  <% end %>
</li>

app/views/shared/_gen_profile_info.html.erb
<div class="row">
  <div class="span12">
      <div class="row">
        <div class="span10">
          <section><%= render 'shared/profile_top_info' %></section>
        </div>

        <div class="span2">
          <section><%= render 'shared/profile_rh_nav' %></section>
        </div>
      </div>
  </div>
</div>

app/views/shared/_grav_name.html.erb
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>

app/views/shared/_lh_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= user_path(@user) %>">
    <strong id="scrawls" class="stat">
      <%= @user.scrawls.count %>
    </strong>
    Scrawls
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    Following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    Followers
  </a>
</div>

app/views/shared/_profile_lh_nav.html.erb
<ul class="nav nav-tabs nav-stacked">
  <li>
    <a href="<%= user_path(@user)%>">Scrawls 	></a>
  </li>
  <li>
    <a href="<%= following_user_path(@user)%>">Following 	></a>
  </li>
  <li>
    <a href="<%= followers_user_path(@user)%>">Followers 	></a>
  </li>
</ul>

app/views/shared/_profile_rh_nav.html.erb
<% if @user.email == current_user.email %>
  <%= link_to "Edit Your Profile", edit_user_path, class: "btn btn btn" %>
<% else %>
  <%= render 'follow_form' if signed_in? %>
<% end %>

<ul class="nav nav-tabs nav-stacked">
  <li>
    <a href="<%= user_path %>">
        <strong><%= @user.scrawls.count %></strong>
        <rhnav>SCRAWLS</rhnav> 
    </a>
  </li>
  <li>
    <a href="<%= following_user_path(@user)%>">
        <strong><%= @user.followed_users.count %></strong> 
        <rhnav>FOLLOWING</rhnav> 
    </a>
  </li>
  <li>
    <a href="<%= followers_user_path(@user)%>">
        <strong><%= @user.followers.count %></strong>
        <rhnav>FOLLOWERS</rhnav> 
    </a>
  </li>
</ul>

app/views/shared/_profile_top_info.html.erb
<a href="<%= user_path %>">
  <%= gravatar_for @user, size: 130 %>
</a>
<ph><%= @user.name %></ph> <br />
<i>
<%= @user.handle	%><br />
</i>
<%= @user.tagline	%><br />
<i>
<%= @user.likes		%>
<%= @user.dislikes	%><br />
</i>
<%= @user.location	%>
<i>
www.facebook.com/<%= @user.fb_url %>
</i>


	

app/views/shared/_scrawl_form.html.erb
<%= form_for(@scrawl) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new scrawl..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
  <a href="<%= user_path(current_user) %>">
    <strong id="scrawls" class="stat">
      <%= @user.scrawls.count %>
    </strong>
    scrawls
  </a>
</div>

app/views/shared/_user_gravitars.html.erb
<% unless @users.empty? %>
	<div class="user_avatars">
	 <% @users.each do |user| %>
	 <%= link_to gravatar_for(user, :size => 50), user %>
	 <% end %>
	</div>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 54 %>
</a>
<h1><%= current_user.name %></h1>
<span>
  <%= link_to "View my profile page", current_user %>
</span>