config/routes.rb
ScrawlSite3::Application.routes.draw do
  
  get "apps/new"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :scrawls,       only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :apps 
  
  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/terms',   to: 'static_pages#terms'

end

app/views/apps/_app.html.erb
<li>
	<%= image_tag(app.image_url, alt: "app.name", class: "round") %>
	<strong><%= link_to app.name, app_path(app) %><br /></strong>
	<%= app.description %> <br />
</li>

app/views/apps/_fields.html.erb
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :version %>
<%= f.text_field :version %>

<%= f.label :description %>
<%= f.text_field :description %>

<%= f.label :tags %>
<%= f.text_field :tags %>

<%= f.label :image_url %>
<%= f.text_field :image_url %>

<%= f.label :longdescription %>
<%= f.text_area :longdescription, :cols => 10, :rows  => 10 %>

<%= f.label :enabled? %>
<%= f.check_box :enabled %>

app/views/apps/edit.html.erb
<% provide(:title, "Edit App") %> 
<h1>Edit App</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@app) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= render 'fields', f: f %>
      <%= f.submit "Save changes", :class => "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/apps/index.html.erb
<% provide(:title, 'Apps') %>
<h1>Apps</h1>

<div class="row">
  <div class="span8 offset4">
	<%= will_paginate %>
	<ul class="apps">
	  <%= render @apps %>
	</ul>
	<%= will_paginate %>
  </div>
</div>

app/views/apps/new.html.erb
<% provide(:title, 'Enter new App') %>
<h1>Enter new App Details</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@app) do |f| %>
    	<%= render 'shared/error_messages', object: f.object %>
      	<%= render 'fields', f: f %> <br /><br />
      	<%= f.submit "Create new App", :class => "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/apps/show.html.erb
<% provide(:title, 'App') %>
<h1><%= @app.name %></h1>

<div class="row">
  <div class="span8 offset2"  >
    <%= image_tag @app.image_url %>
    <br /><br />
    <%= @app.longdescription %>
  </div>
</div>